name: flutter_kaldi_libs
description: A new Flutter plugin project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.12.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  plugin:
    platforms:
      android:
        package: com.example.flutter_kaldi_libs
        pluginClass: FlutterKaldiLibsPlugin
      ios:
        pluginClass: SwiftFlutterKaldiLibsPlugin
      linux:
        pluginClass: FlutterKaldiLibsPlugin
